### PR TITLE
Refactoring to root feature directory

### PR DESCRIPTION
**Pull request by PapyElGringo**
In order to reduce the length of the encapsulated file tree I decided to switch to a more classic approach of root feature tree and in order to split to big provider files into separated independent file I decided to move to the `provider` `model` `widget` structure

### CODE REVIEW

**Comment by roscale** [comment]
@PapyElGringo 

Is this supposed to compile? Because it doesn't compile on my machine. I think some imports to generated files are incorrect.

**Comment by roscale** [comment]
Also, I see that `window/widget/window.dart` is entirely commented. I don't know if it's supposed to be intentional or not, just pointing this out. I see other blocks of commented code.

**Comment by PapyElGringo** [comment]
> @PapyElGringo 
> 
> Is this supposed to compile? Because it doesn't compile on my machine. I think some imports to generated files are incorrect.

Well it was supposed to work I need to test on a fresh clone

**Comment by PapyElGringo** [comment]
ok fixed

**Review by roscale — APPROVED** [review]
You still have some commented code like `wayland/provider/xdg_surface.dart`. You can do a global search for /* or // to check, but other than that, ok, I don't have anything to add.

**Comment by PapyElGringo** [comment]
Yeah the commented code that remain it's because I know I didn't reimplemented all feature yet of this file

**Pull request merged**
